{
 "title": "HTTP App",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": "app" },
   { "name": "port", "query": "8888" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Success request rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{instance=\"$app:$port\", code=\"200\"}[5m]))"
    }
   ]
  },
  {
   "title": "Error during the last $interval",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{instance=\"$app:$port\", code=~\"^5[0-9]{2}$\"}[$interval])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Error during the last 5 min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{instance=\"$app:$port\", code=~\"^5[0-9]{2}$\"}[5m])) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Max Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(http_request_duration_microseconds_sum{instance=\"$app:$port\"}[30s])/rate(http_request_duration_microseconds_count{instance=\"$app:$port\"}[30s]) > 0) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Calls/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=\"$app:$port\"}[30s])) by (handler) ",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Success request rate (2xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "req / s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{instance=\"$app:$port\", code=~\"2[0-9]+\"}[5m]))",
     "legendFormat": "count"
    },
    {
     "expr": "avg(irate(http_request_duration_microseconds_sum{instance=\"$app:$port\"}[5m])/irate(http_request_duration_microseconds_count{instance=\"$app:$port\"}[5m]) > 0)",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Client error request rate per second (4xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{instance=\"$app:$port\", code=~\"4[0-9]+\"}[5m]))",
     "legendFormat": "4xx"
    }
   ]
  },
  {
   "title": "Server error request rate per second (5xx)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{instance=\"$app:$port\", code=~\"5[0-9]+\"}[30s])) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  }
 ]
}